### PR TITLE
Mirrors Backbones Model.attributes property

### PR DESCRIPTION
**Pull request by snurra**
Backbone relies on `Backbone.Model.attributes` internally for methods like `Backbone.Model.clone` and `Backbone.Model.changedAttributes`. Since we expand all relations to proper models and collections we remove them from the attributes object to avoid complications/confusion - but this also means that their data isn't there when Backbone expects it to be.

This PR makes sure that related objects are returned as JSON whenever `Backbone.Model.attributes` is used.

### CODE REVIEW

**Comment by snurra** [comment]
@martinlissmyr What do you think?

**Comment by martinlissmyr** [comment]
Nice!

**Comment by snurra** [comment]
Perfomance-wise it's not ideal. But since this should make Backbone-kinship more compatible with Backbone without having to rewrite every Backbone method that uses attributes directly (and without having to explicitly tell developers not to expect `Backbone.RelationalModel.attributes` to contain relational data) I think this is a good thing.

**Comment by martinlissmyr** [comment]
Yes, good job!

**Comment by martinlissmyr** [comment]
@snurra but you closed it?

**Comment by snurra** [comment]
I did?! I will never learn to drive this Github machine.

**Comment by martinlissmyr** [comment]
Github: chow

**Pull request merged**
